### ISSUE TITLE
账号密码是啥啊？

### ISSUE THREAD

**Issue by b12738566** [maohuihua123/spring-boot-picture-copyright#6]
Using generated security password: 35cec4ec-99aa-4c7c-8004-952f9873fb8b
已经运行出这个了，账号和密码是什么呢？

**Comment by maohuihua123** [comment]
晕，你这是使用了Spring Security，应该使用Spring Security的密码

**Comment by maohuihua123** [comment]
账号就是：钱包文件，密码就是注册时的密码

**Comment by b12738566** [comment]
好的大佬，已经读取到文件了，但是输入注册时的密码还是错误了（不知道哪里错了）。。。以下是文件信息：
{"address":"4447e8f81a52613f5fa2442002b4c541a5d99528","id":"c4cad3cc-4cc3-44a0-b0f2-7bbc63176c0d","version":3,"crypto":{"cipher":"aes-128-ctr","ciphertext":"9c56353a6953cbc35ccc86e9f6dfbf9e4a4dc5b127378e3bd2080d7297b539ee","cipherparams":{"iv":"ca29d60b25d5a87338081716789ef635"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"377b34f44802f10b8a42b6effec8746fb5383e76f7d6c9a715fddfacae8c45f3"},"mac":"c531e86bf42ef8affa2af81b3c0950b95e18097858ecf13a3108e1f22d7954da"}}

![image](https://github.com/maohuihua123/spring-boot-picture-copyright/assets/131446456/98382480-4912-4141-9bef-ea85b5d3e303)

**Comment by b12738566** [comment]
大佬，我调试的版本是回退到历史的第二版本（有前端的），求教求教
![image](https://github.com/maohuihua123/spring-boot-picture-copyright/assets/131446456/b642a23f-7048-4947-bb46-500e4707dce3)
